### ISSUE TITLE
CIFAR-10 net

### ISSUE THREAD

**Issue by Alexey-Kamenev** [gcr/torch-residual-networks#2]
Hi Michael,
I'm curious why do you need this in your CIFAR-10 config:

```
model = addResidualLayer2(model, 64, 10, 1)
```

Why not just feed last convolutional layer directly to avg pooling?
E.g:

```
for i=1,N do   model = addResidualLayer2(model, 64)   end
------> 64, 8,8     Pooling, Linear, Softmax
model = nn.SpatialAveragePooling(8,8)(model)
```

I think this is how it's done in the paper.

**Comment by gcr** [comment]
Oh, good point. I wasn't sure what to do here.

Hmm. So this would lead to a `64x1x1` input. Does their fully-connected layer take 64 channels and downsample it directly to 10? I was thinking the fully-connected layer takes 10 as input (hence the need for downsampling here) and outputs 10 as output, but maybe that isn't right...

**Comment by Alexey-Kamenev** [comment]
What you have after avg pooling is 64x1x1 as you pointed out. Then you just have a fully connected layer, 10x64.

**Comment by Alexey-Kamenev** [comment]
And another, albeit unrelated, question: in cifar_dataset.lua, it looks like test set size is set to 2000:
`local tesize = 2000`
Isn't it really 10K? I'm not familiar with Lua/Torch enough so I guess I'm missing something here.

**Comment by gcr** [comment]
D'oh! I'm an idiot. You're absolutely right about the test size. That's a typo. No wonder each evaluation run takes less than a second!

Adding insult to injury, I received a wonderful email from Kaiming today with some theories about why my results seemed to be less stable than the ones in the paper. We now know it's because of the smaller test size. I'll begin rerunning these experiments now and update the README with my results when they finish. Oops...

Thanks for catching that.

**Comment by Alexey-Kamenev** [comment]
No worries, it's usually a good idea to have another pair of eyes to look at the code :)
Just FYI, I'm working on reproducing ResNet results as well, but using CNTK instead of Torch.
Here is my result so far (only for CIFAR-10 20-layer net for now):
https://cntk.codeplex.com/SourceControl/latest#Examples/Image/Miscellaneous/CIFAR-10/Output/03_ResNet_Train_AddBNEval_Test.log.160
Scroll down to the very end, you should see something like ErrorPrediction/Sample = 0.0819
Configs and other files:
https://cntk.codeplex.com/SourceControl/latest#Examples/Image/Miscellaneous/CIFAR-10/

It would interesting to compare results of our experiments on ImageNet.

**Comment by gcr** [comment]
Just changed the architecture and evaluated on all 10k CIFAR images. My results look much more stable... thanks again for the clues!

I might try to run this on imagenet next. We'll see if it works...
