### ISSUE TITLE
How to use lab-workbook in train-cifar.lua

### ISSUE THREAD

**Issue by lim0606** [gcr/torch-residual-networks#4]
Hi, 

First of all, thank you for sharing your review work. 

It seems that `lab-workbook` is required to make snapshot in `train-cifar.lua`; thus I installed it with your repository (https://github.com/gcr/lab-workbook). 

However, this package asked me to have a configuration file `~/.lab-workbook-config`, and I have no idea how to set it. 

Is there anyone who help me to use it? 

I would also appreciate if someone let me know I can snapshot weights with other methods. I used to use caffe and I'm new to lua and torch. 

Thanks,

**Comment by gcr** [comment]
oops! sorry! i've been meaning to document `lab-workbook` for a while.

It's probably best to simply replace all the workbook calls with your own calls to `torch.save()` and `print()`. The idea behind the lab workbook is to stream all of your experiment results (loss, error, models) to Amazon S3, so you don't have to worry about keeping them on the filesystem. This is super helpful if you have several machines running at once.

If you want to use the lab workbook:
- Install the AWS command line tools. This is the `awscli` Python package, so if you use pip, try `pip install awscli`
- Save your AWS credentials into `~/.aws/credentials`:

```
[default]
aws_access_key_id = 123456abcdefgh
aws_secret_access_key = 123456abcdefgh
```

At this point, the `aws` command should be  on your `$PATH` and `aws list` should list all of your S3 buckets.
- Make an S3 bucket to save experiment results
- Create `~/.lab-workbook-config` with the content:

```
bucketPrefix = s3://bucket-name-here/path/to/experiments/
```

This will save the results of all experiments to the `/path/to/experiments/` prefix in the `bucket-name-here` S3 bucket. (Make sure this prefix ends in `/`).

Every time you run your code, it creates a new experiment and prints the random experiment ID. You can then save this ID and analyze the results in an IPython notebook running on your laptop or whatever (see [example](https://github.com/gcr/torch-residual-networks/blob/master/Residual%20Network%20Experiment%20Results.ipynb)).

Again, sorry this isn't documented very well. If you don't want to fight with it, you can just replace everything with calls to `print` and `torch.save` to save yourself the trouble...

**Comment by lim0606** [comment]
@gcr 

Thank you for kind response!

I tried to use `lab-workbook` and `aws-cli` as you suggested, but I couldn't. 

I followed some instructions from here
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-set-up.html
http://docs.aws.amazon.com/cli/latest/userguide/installing.html#cli-test-the-setup
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

However, `aws` keep saying

```
A client error (InvalidAccessKeyId) occurred when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records.
```

I thinks I will use `torch.save()` and `print()` for now. 

Once again, thank you for your assistance. 

Jaehyun

**Comment by lim0606** [comment]
It was the problem of credentials. I think the credential I copied somehow changed by myself. I made a new use, and the problem solved. 

Thank you so much! The `lab-workbook` seems really helpful :)

**Comment by gcr** [comment]
glad (and mildly surprised) it works for you!

if others find this thread in the future, perhaps running `aws configure` is a good way to set the credentials at first

**Comment by dasguptar** [comment]
@gcr Could you maybe add some documentation for `lab-workbook`?

**Comment by gcr** [comment]
Sure, @dasguptar ! Here's some documentation for the `lab-workbook` library:

https://github.com/gcr/lab-workbook#readme

Hope this helps!

If you don't like this library, I hope it's pretty easy to replace all the calls with logging/saving of your choice. It should be pretty self-evident what each call is doing...
